### PR TITLE
Stylelint configuration

### LINKED ISSUE #27: Add style linting
- [x] Investigate adding a style linting tool for CSS/Sass files. Possible options include [Stylelint (preferred)](https://stylelint.io/), [scss-lint,](https://github.com/sds/scss-lint) and sass-lint.
- [x] Create general linting config for baseline:
  - newline before/after brackets in declaration blocks
  - newline per declaration
  - space between properties and values
  - enforce semicolon use when ending declarations
  - favor double-quotes (`"`) over single-quotes (`'`)
  - enforce leading zeroes in decimal values
  - lowercase props and values
- [x] Follow-up: solicit feedback from UXD group for consensus on linting rules on spacing
  - declaration order and grouping
  - spaces vs tabs 😨
  - maximum nesting depth
  - media query approaches and placement
  - disallowing redundant declarations, ex. `margin: 0;` followed by `margin-right: 10px;`
  - allow or disallow use of `extend`

### PR DESCRIPTION
**Pull request by teenwolfblitzer**
## Description
Sage CSS linting configuration. Follows patterns drawn from UXD style survey.

VSCode:
linting-vscode

Atom:
linting-atom

Rules/guidelines
**default violations give a warning, rules marked with a * are enforced and throw an error**

- [x] newline before/after brackets in declaration blocks*
- [x] newline per declaration
- [x] no empty blocks *
- [x] space between properties and values
- [x] enforce semicolon use when ending declarations
- [x] favor double-quotes (`"`) over single-quotes (`'`) *
- [x] enforce leading zeroes in decimal values *
- [x] lowercase property names *
- [x] lowercase values *
- [x] single space between values and properties *
- [x] pseudo-elements require double colon (`::`)
- [x] font-family names should be surrounded by quotes(`"`) *
- [x] "named" colors (ex. `black`, `skyblue`) are only allowed within functions
- [x] no empty comments (`/* */`) *
- [x] 3 level max nesting depth
- [x] whitespace between comment opening/closing marks and contents 
- [x] duplicate properties are _not_ allowed unless consecutive (ex. CSS custom property fallbacks) *
- [x] limit of 2 empty lines in declaration blocks
- [x] animations that aren't defined in `@keyframes` disallowed *
- [x] single space required between multiple comma-separated `@media` declarations *
- [x] disallow use of `!important` (can be overridden with `/* stylelint-ignore */`) in special cases

### Steps for testing
An example with comments for rules/guidelines can be found [here](https://gist.github.com/monkeypox8/88424b7baf6a2e9de86cd766d4f314c1).

Linting can be performed from the command line, but is much more convenient via your [editor of choice](https://stylelint.io/user-guide/integrations/editor).

CLI steps:
1. Run `bundle` and `npm i` from the parent `sage` directory to install dependencies
2. `npx stylelint <stylesheet file path>` to lint files. ex: `npx stylelint "app/assets/**/*.scss"` will check and lint the entire assets directory (warning: it's a long list)

Code editor steps:
1. Run `bundle` and `npm i` from the parent `sage` directory to install dependencies
2. Download, install, and enable the appropriate integration for your editor from [stylelint](https://stylelint.io/user-guide/integrations/editor)
3. Open a `.scss` file in Sage
4. ???
5. [Profit](https://www.youtube.com/watch?v=tO5sxLapAts)

## Related issues
-  Resolves #27

### CODE REVIEW

**Review by AndrwM — APPROVED** [review]
omgswag 👍 

I wonder what it would take to have this validated at the PR level too with a tool like Hound or something similar. https://www.houndci.com/

Hound leaves warnings when a PR is opened in github. This may be too heavy handed altogether because it can overload a PR with comments but could be worth experimenting with.

**Comment by AndrwM** [comment]
We're also all subject matter experts when it comes to styles too so that may be just too much. Probably tooling overload for now.

**Comment by teenwolfblitzer** [comment]
> Hound leaves warnings when a PR is opened in github. This may be too heavy handed altogether because it can overload a PR with comments but could be worth experimenting with.

I think this is a great idea to explore. It'd help speed up the PR process and the learning curve for anyone unfamiliar with the guidelines we're trying to establish. I wonder if it'd be possible to add to the "main" repo as well.

I was also looking into integrating linting in the build process, which could be a less intrusive approach.

**Comment by AndrwM** [comment]
I'd say linting in the build process would be much cleaner. That way the PR is "red" until it meets stylelint guidelines but keeps the noise down in the PR. Good idea. 💯

**Review by philschanely — APPROVED** [review]
🏆🏆🏆!!!

**Comment by philschanely** [comment]
FTR I am in favor of linting as part of PR pass/fail checks that are automated as a measure to ensure the author lints before merging. Should not be something we have to critique in PRs but assume is being done. 2¢

**Comment by teenwolfblitzer** [comment]
Follow-up issue for integrating linting with the build process: #75

**Pull request merged**
