### PR TITLE
Update quick links module

### PR DESCRIPTION
**Pull request by philschanely**
Cleans up the Quick Links sidebar structure to use simpler BEM.

### CODE REVIEW

**Review by cmcfadzean — APPROVED** [review]
Like it

**Review by teenwolfblitzer — APPROVED** [review]
👍Looks good to me, great work!  One thing I'm wondering is whether we alter the link structure to use an unordered list rather than the current stack of anchor links. I'll leave it up to you whether we take this on in a follow-up or should even address at all.

**Comment by philschanely** [comment]
@monkeypox8 definitely in favor of the ul standard. I'll work that in...

**Review by teenwolfblitzer — APPROVED** [review]
👍 Nice work!

**Pull request merged**
