### PR TITLE
Revise tabs spacing settings, add divider

### PR DESCRIPTION
**Pull request by philschanely**
## Description

Revises tabs spacing settings and adds an optional divider element.

### Screenshots

Screen Shot 2020-09-30 at 10 46 20 AM

Affected Products aspects PR drafted: https://github.com/Kajabi/kajabi-products/pull/15852

### CODE REVIEW

**Review by pixelflips — APPROVED** [review]
👍  LGTM! One minor thing that I did notice is that the choice tabs break out of their container on smaller screen sizes, but that doesn't appear related to these updates. Not a show stopper, but might be worth noting for a future adjustment. Nice work!

**Review by joe-dakroub — APPROVED** [review]
Nice updates; much tighter. Looking good Phil! 👍

**Review by teenwolfblitzer — APPROVED** [review]
👍 🚢 Looks great! Thoughts on removing the "old" tab item in Elements?

**Comment by philschanely** [comment]
@pixelflips That's a great point. I'll look at that on the next task to add those arrows to the choice components.

@joedakroub thanks! 🙇‍♂️ 

@monkeypox8 Ah! Yes; I'll do a little cleanup like that in a separate followup. Thanks!!

**Pull request merged**
