### PR TITLE
Sidenav style updates

### PR DESCRIPTION
**Pull request by teenwolfblitzer**
## Description

- Revises sidebar nav/link styles to match [updated Figma comps](https://www.figma.com/file/xlUFoRTjsFePavVT85SmLL/Sage-Design-System-v1.0?node-id=2322%3A6093)
- Sidebar and content backgrounds updated to more closely align with `kajabi-products` styling

|  In use   |  Display states  |
|--------|--------|
||sidenav-states|

|  before   |  after  |  app view |
|--------|--------|--------|
|sidenav-before|sidenav-after|app-current|

## Related

- n/a

### CODE REVIEW

**Review by pixelflips — APPROVED** [review]
🚀   - LGTM!

**Review by AndrwM — APPROVED** [review]
Nice! This looks great.

I wonder what the team thinks about having some type of "Pro"/"Compact" spacing/text-sizing for this that can be used within Super Admin and Sage Docs. The amount of links that we display on Admin compared to the others is significantly less. It's starting to feel like the Sage Docs are a bit unusable with all the links we're stuffing in there.

**Review by philschanely — APPROVED** [review]
Nice! 🙌

**Comment by philschanely** [comment]
> Nice! This looks great.
> 
> I wonder what the team thinks about having some type of "Pro"/"Compact" spacing/text-sizing for this that can be used within Super Admin and Sage Docs. The amount of links that we display on Admin compared to the others is significantly less. It's starting to feel like the Sage Docs are a bit unusable with all the links we're stuffing in there.

Perhaps we don't need to display the submenus under Elements and Objects anymore. They also both have the on-page navigation on the right side?

**Comment by teenwolfblitzer** [comment]
> > Nice! This looks great.
> > I wonder what the team thinks about having some type of "Pro"/"Compact" spacing/text-sizing for this that can be used within Super Admin and Sage Docs. The amount of links that we display on Admin compared to the others is significantly less. It's starting to feel like the Sage Docs are a bit unusable with all the links we're stuffing in there.
> 
> Perhaps we don't need to display the submenus under Elements and Objects anymore. They also both have the on-page navigation on the right side?

👍 I like the idea of removing the submenus from the overviews of both, since the list is bound to grow even longer in the near future. I'll open a follow-up issue to investigate.

**Pull request merged**
