### PR TITLE
Convert table markup to .erb

### PR DESCRIPTION
**Pull request by pixelflips**
- [x] Create table markup file
- [x] Update markup and preview files

### CODE REVIEW

**Review by philschanely — APPROVED** [review]
Would you consider allowing this to accept a collection that it parses to rows and cells? Not blocking this implementation though.

**Comment by pixelflips** [comment]
> Would you consider allowing this to accept a collection that it parses to rows and cells? Not blocking this implementation though.

@philschanely - sure! care to elaborate though so I am sure I understand. I think you mean possibly being able to pass in data for the column headers as an example?

**Comment by philschanely** [comment]
Yeah something like that; some form of being able to call the partial and pass in a data set, rather than the partial always showing the same fixed data. No biggie.

**Comment by philschanely** [comment]
And by "no biggie" I mean its ok if its something we put in a separate task.

**Pull request merged**
