### PR TITLE
Sortable: Match New Comps

### PR DESCRIPTION
**Pull request by AndrwM**
## Description
Updates Sortable default styles to match new comps.
https://www.figma.com/file/TO8XSqt6tgscFcShhkWVdm/Products-Admin?node-id=1008%3A3304

### Screenshots

|  before  |  after  |
|--------|--------|
|image|image|

### Steps for testing
n/a, this is only lipstick :)

## Related
https://github.com/Kajabi/kajabi-products/pull/16475

### CODE REVIEW

**Review by pixelflips — APPROVED** [review]
LGTM! 👍

**Review by philschanely — COMMENTED** [review]
Work looks good here @AndrwM . Two related questions:

- In the core components I see there should still be a panel list style distinct from a card style but these changes seem to have affected the panel list style (see the [preview page](https://sage-ajm-sortable-polis-02nxro.herokuapp.com/pages/breakout/object/sortable) and then [this mock](https://www.figma.com/file/SCZt9jMd7OcTMrNsOFifDp/Sage-Components-WIP?node-id=768%3A25)). Is this intentional? 
- If we don't need/want the list style anymore, we can probably remove the `SagePanelList` wrapper on the preview page for that group.

**Comment by AndrwM** [comment]
@philschanely Yep! That's intentional. Hmm.. Looks like the system hasn't been updated even though our Build comps are. I'll reach out to design.

**Review by joe-dakroub — APPROVED** [review]
Style changes look good. Nice design update! 👍

**Comment by philschanely** [comment]
> @philschanely Yep! That's intentional. Hmm.. Looks like the system hasn't been updated even though our Build comps are. I'll reach out to design.

Great, @AndrwM I might have an outdated version myself. Could you please update the preview page accordingly? Is there still a need to distinguish the two types?

**Pull request merged**
